### ISSUE TITLE
Cannot remove interceptor on axios

### ISSUE THREAD

**Issue by shaynlink** [dobesv/axios-oauth-1.0a#132]
We can not remove interceptor like this example:
```js
const myInterceptor = axios.interceptors.request.use(function () {/*...*/});
axios.interceptors.request.eject(myInterceptor);
```
Because `addOAuthInterceptor` don't return interceptor.

Remove interceptor is useful if we using multiple auth method, like twitter that use Oauth1a, Oauth2 PKCE, Oath2 Bearer only, and other.

**Comment by dobesv** [comment]
I released this to npm
