### ISSUE TITLE
Initials become lowercase to uppercase？

### ISSUE THREAD

**Issue by hjMaGitHub** [dobesv/axios-oauth-1.0a#134]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/40014076/185020626-365d7fca-fb81-4fe2-beed-0872b6e50b73.png">
Hello, can the authorization in the request header be set to Authorization?
Initials become lowercase to uppercase

**Comment by dobesv** [comment]
HTTP headers are not case-sensitive, it shouldn't be necessary to change this.
