### ISSUE TITLE
Release update version about  "axios": "^0.19.2"  to  "axios": "^0.21.1" 

### ISSUE THREAD

**Issue by OnurSevket** [dobesv/axios-oauth-1.0a#17]
Hi,

I shared a screen-shot.Can you update axios release version?

![image](https://user-images.githubusercontent.com/23638184/118414279-5284d800-b6ac-11eb-95c2-a2962494d80c.png)

**Comment by dobesv** [comment]
Can't you just install any axios version you want?

**Comment by OnurSevket** [comment]
I did not understand,How can i do?Please,Could you explain it?

**Comment by dobesv** [comment]
If you run `npm i axios` will it install the latest version of `axios` ?

**Comment by OnurSevket** [comment]
yes i am using latest version axios,But this package(
axios-oauth-1.0a) usage axios 0.19.2 version,So I'm not include dependency my project.You should upgrade the version on NPM.I added screenshot about "axios-oauth-1.0a".

![image](https://user-images.githubusercontent.com/23638184/118539137-bc0df080-b757-11eb-95d1-3b4f5e779e27.png)

**Comment by dobesv** [comment]
Hi,

It doesn't matter what dependency this project lists in its `peerDependencies` or `devDependencies` as it will use whichever version you are using in your own project.  Those dependency versions on affect the version of `axios` used to develop on this library.

**Comment by OnurSevket** [comment]
thank you for publishing ,now I added the dependency

![image](https://user-images.githubusercontent.com/23638184/118546485-b23cbb00-b760-11eb-83c9-da03ca54d4f6.png)
