### ISSUE TITLE
Missing documentation / support to add oauth_callback and other oauth_* headers

### ISSUE THREAD

**Issue by deCodeIt** [dobesv/axios-oauth-1.0a#25]
Services like Twitter need oauth_callback and oauth_version headers.
I couldn't find the documentation to use it with this package.
Any pointers?

**Comment by dobesv** [comment]
`oauth_version` is set automatically.  I guess there's no support for `oauth_callback` currently.  You'd have to add a PR for that, maybe.

Doesn't twitter use OAuth 2.0 by now, though ?

**Comment by dobesv** [comment]
Actually, if you add `oauth_callback` to the request either in a form POST body or a query parameter it should be passed through unchanged and also be included in the signature calculation.

**Comment by dobesv** [comment]
But it's not added to the `Authorization` header.  If twitter requires it to be in the `Authorization` header you'd have to modify the library.

**Comment by goleary** [comment]
FWIW it doesn't look like passing it in the post body request works, so it sounds like the library requires modification to support this.

> Doesn't twitter use OAuth 2.0 by now, though ?

No, they do not use OAuth 2.0 for user context authentication.

**Comment by rodrigowbazevedo** [comment]
I created a PR #56 to add support to oauth callback.

**Comment by dobesv** [comment]
Fixed in #56
