### ISSUE TITLE
addOAuthInterceptor is not a function

### ISSUE THREAD

**Issue by Leigh-M** [dobesv/axios-oauth-1.0a#4]
There were some issues with installing dependencies, but once removed all axios versions up the dependency tree it did install but not cleanly 2 high severity warnings. Will they be addressed at some stage for easy/ secure automated installs? Thanks

**Comment by dobesv** [comment]
Can you provide more details?

**Comment by Leigh-M** [comment]
Hello, thanks for checking. It was a problem on Ubuntu 20.04LTS with node v10. (I was using that version to emulate AWS SAM local which runs on v10 only currently) when upgraded to node v12 then dependency resolution issue was also resolved. 

Thanks and please do close this ticket


For anyone else that runs into the same issue, resolve as above:

npm i axios-oauth-1.0a
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: oauth@1.0.0
npm ERR! Found: axios@0.21.1
npm ERR! node_modules/axios
npm ERR!   axios@"^0.21.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer axios@"^0.19.2" from axios-oauth-1.0a@0.2.1
npm ERR! node_modules/axios-oauth-1.0a
npm ERR!   axios-oauth-1.0a@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

npm ERR! A complete log of this run can be found in:
