### ISSUE TITLE
Module not found: Error: Can't resolve 'crypto' in

### ISSUE THREAD

**Issue by Smartmikey** [dobesv/axios-oauth-1.0a#84]
I'm planning to use this in my react app for woocommerce request but I get this error

**Comment by swa-dev** [comment]
I am having the same issue and unable to resolve it. There is mention of adding a polyfill. Is that just a bandaid or the true solution (unsure how to do that either way)

**Comment by dobesv** [comment]
If you are using `webpack` you can use `resolve.fallback` to supply a browser-compatible `crypto` module:

https://webpack.js.org/configuration/resolve/#resolvefallback

Other environments may have something similar.
