### ISSUE TITLE
Uncaught (in promise) ReferenceError: Buffer is not defined at calculateBodyHash

### ISSUE THREAD

**Issue by swa-dev** [dobesv/axios-oauth-1.0a#89]
After adding resolve.fallback, I am receiving the following error:

`Uncaught (in promise) ReferenceError: Buffer is not defined at calculateBodyHash` which looks to be referencing line 19 in index.ts

**Comment by dobesv** [comment]
Can try adding this to plugins:

```
new ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
        process: 'process/browser',
      }),
```

**Comment by dobesv** [comment]
I added a note in the readme as well, please let me know if it's helpful.

**Comment by swa-dev** [comment]
I gave this a try, but am still receiving the same error. My webpack config was generated from create-react-app. However, I still placed in:

```
module.exports = function (webpackEnv) {
// ...
   return{
         plugins: [
               new webpack.ProvidePlugin({
                   Buffer: ['buffer', 'Buffer'],
                   process: 'process/browser',
               }),
         ],
   }
// ...
}
```

**Comment by dobesv** [comment]
OK, sorry I guess you'll have to figure it out.  I don't know.

**Comment by swa-dev** [comment]
Just wanted to add for anyone else trying to use this with React. The issue was resolved by:
- Adding the Buffer to plugins, per dobesv's comment
> Can try adding this to plugins:
> 
> ```
> new ProvidePlugin({
>     Buffer: ['buffer', 'Buffer'],
>     process: 'process/browser',
> }),
> ```
- Deleting the /node_modules/.cache/ directory
