### ISSUE TITLE
axios-oauth-1.0a not working with webpack v5

### ISSUE THREAD

**Issue by jsuazod** [dobesv/axios-oauth-1.0a#90]
When creating a react app using npx create-react-app now it comes with webpack v5, it seams that this package does not support it, when i try using it throws this error:

ERROR in ./node_modules/axios-oauth-1.0a/dist/index.js 25:31-48

Module not found: Error: Can't resolve 'crypto' in '/Users/jsuazo/Code/test/my_ap/node_modules/axios-oauth-1.0a/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

**Comment by dobesv** [comment]
I think you'll have to follow the instructions given to add the polyfill.
